### PR TITLE
Upgrade Robolectric to 4.6.1

### PR DESCRIPTION
**Pull request by sshropshire**
### Summary of changes

 - Upgrade Robolectric to version `4.6.1`
 - Fixup some tests that were failing after update

 ### Checklist

 ~- [ ] Added a changelog entry~

### Authors

- @sshropshire

### CODE REVIEW

**Comment by sarahkoop** [comment]
Do we need to bump to Java 11 in GitHub Actions for this change?

**Comment by sshropshire** [comment]
> Do we need to bump to Java 11 in GitHub Actions for this change?

Yeah good call. I can bump.

**Comment by sarahkoop** [comment]
Would it make sense to set compileOptions to Java 8 (or even Java 7?) in the demo app to make sure we don't introduce any incompatible changes in the SDK?

**Comment by sshropshire** [comment]
> Would it make sense to set compileOptions to Java 8 (or even Java 7?) in the demo app to make sure we don't introduce any incompatible changes in the SDK?

Decided to go with explicit Java 7 support until we can investigate to see if browser switch creates an implicit Java 8 requirement.

**Pull request merged**
